import type {Edge, Node} from "@xyflow/react";

export const algebraNodes : Node[] = [
    {
        id: "A",
        position: { x: 0, y: 0 },
        type: "subject",
        data: {subjectName: "Subject A"},
        style: {
            width: 500,
            height: 300,
        },
    },
    {
        id: "B",
        position: { x: 0, y: 380 },
        type: "subject",
        data: {subjectName: "Subject B"},
        style: {
            width: 500,
            height: 300,
        },
    },
    {
        id: "1",
        position: { x: 60, y: 30 },
        type: "topic",
        data: { topic: "subj1-topic1", topicName: "Topic 1" },
        parentId: "A",
        extent: "parent",
    },
    {
        id: '2',
        position: { x: 335, y: 30 },
        type: "topic",
        data: { topic: "subj1-topic2", topicName: "Topic 2" },
        parentId: "A",
        extent: "parent",
    },
    {
        id: '3',
        position: { x: 60, y: 210 },
        type: "topic",
        data: { topic: "subj1-topic3", topicName: "Topic 3" },
        parentId: "A",
        extent: "parent",
    },
    {
        id: '4',
        position: { x: 335, y: 210 },
        type: "topic",
        data: { topic: "subj1-topic4", topicName: "Topic 4" },
        parentId: "A",
        extent: "parent",
    },
    {
        id: "5",
        position: { x: 60, y: 30 },
        type: "topic",
        data: { topic: "subj2-topic1", topicName: "Topic 5" },
        parentId: "B",
        extent: "parent",
    },
    {
        id: '6',
        position: { x: 335, y: 30 },
        type: "topic",
        data: { topic: "subj2-topic2", topicName: "Topic 6" },
        parentId: "B",
        extent: "parent",
    },
    {
        id: '7',
        position: { x: 60, y: 210 },
        type: "topic",
        data: { topic: "subj2-topic3", topicName: "Topic 7" },
        parentId: "B",
        extent: "parent",
    },
    {
        id: '8',
        position: { x: 335, y: 210 },
        type: "topic",
        data: { topic: "subj2-topic4", topicName: "Topic 8" },
        parentId: "B",
        extent: "parent",
    },
];

export const algebraEdges : Edge[] = [
    {
        id: 'e1-2',
        source: '1',
        target: '2',
        sourceHandle: "right",
        targetHandle: "left",
    },
    {
        id: 'e2-3',
        source: '2',
        target: '3',
        sourceHandle: "bottom",
        targetHandle: "top",
    },
    {
        id: 'e2-4',
        source: '2',
        target: '4',
        sourceHandle: "bottom",
        targetHandle: "top",
    },
    {
        id: 'e5-6',
        source: '5',
        target: '6',
        sourceHandle: "right",
        targetHandle: "left",
    },
    {
        id: 'e6-7',
        source: '6',
        target: '7',
        sourceHandle: "bottom",
        targetHandle: "top",
    },
    {
        id: 'e6-8',
        source: '6',
        target: '8',
        sourceHandle: "bottom",
        targetHandle: "top",
    },
    {
        id: 'eA-B',
        source: 'A',
        target: 'B',
        sourceHandle: "bottom",
        targetHandle: "top",
    },
];